version: '2'

networks:
  evault:

services:
  redis1:
    image: 'redis:latest'
    container_name: redis.judge.lithium.com
    command: redis-server --requirepass judgelithium
    ports:
      - "6379:6379"
    networks:
      - evault

  redis2:
    image: 'redis:latest'
    container_name: redis.lawyer.lithium.com
    command: redis-server --requirepass lawyerlithium
    ports:
      - "6380:6379"
    networks:
      - evault



